system("grep GC_CpgIslands #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb > #{@outputDir}/new_Summary")
    system("grep 3UTR_Gene__RefSeq #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep 3UTR_Known__Gene #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep 5UTR_Gene__RefSeq #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep 5UTR_Known__Gene #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep Gene__RefSeq #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep Intron_Gene__RefSeq #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep Intron_Known__Gene #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep Known_Gene #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep Promoter_Gene__RefSeq #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep Promoter_Known__Gene #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep Repeat_DNA #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep Repeat_LINE#{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep Repeat_LowComplex #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep Repeat_LTR #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep Repeat_Other #{@outputDir}/#{@readName}.trackCoverage.lff| cut -f,10,10 | rubySumInput.rb >> #{@outputDir}/new_Summary")
    system("grep Repeat_RNA #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep Repeat_Satellite #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep Repeat_Simple #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep Repeat_SINE #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep Repeat_Unknown #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep miRNA #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep piRNA #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep scaRNA #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
    system("grep snoRNA #{@outputDir}/#{@readName}.trackCoverage.lff | cut -f,10,10 | rubySumInput.rb>> #{@outputDir}/new_Summary")
