require 'brl/genboree/tools/reasoner/reasonerRulesHelper'

module BRL; module Genboree; module Tools;
  class Reasoner21RulesHelper < ReasonerRulesHelper
    TOOL_ID = "reasoner-2.1"

    # @see http://genboree.org/REST/v1/grp/ClingenAutomatedInference/kb/ClingenInferenceEngineAlpha/coll/GuidelineRules_0.2/model?
    def getRulesModel
      model = %Q@{"required":true,"name":"GuideLines_V0_2","domain":"regexp([A-Za-z0-9]+-Guidelines)","unique":true,"description":"For example, ACMG OR McArthurLabGuideLines","identifier":true,"properties":[{"name":"Rules","items":[{"required":true,"name":"Rule","category":true,"domain":"string","unique":true,"description":"A rule item / sub-doc / record)","identifier":true,"properties":[{"required":true,"name":"Conditions","items":[{"required":true,"name":"Condition","domain":"string","unique":true,"description":"A condition item / sub-doc / record","identifier":true,"properties":[{"required":true,"name":"PartitionPath","domain":"string","description":"What partition does this condition examine? Period-delimited path [of keys] in the partitioned \\"data\\" section of the partitioning transformation output."},{"required":true,"name":"Condition","domain":"regexp(^[>,=]=\\\\d)","description":"What is the conditional test applied to the value for PartitionPath? A string encoding a simple conditional test for the value in that partition"},{"name":"AggregationOperation","domain":"enum(sum, count, value)","description":"How to aggregate multiple values when coming up with the value for PartitionPath, if ParttionPath does not point to a \\"leaf\\" or final value, but rather to a partition that has multiple values (i.e. it indicates a whole \\"column\\" which thus can have multiple values, yes?)"}]}],"fixed":true,"domain":"[valueless]","description":"The list of conditions for this rule. Each rule has 1+ conditions to test."},{"required":true,"name":"Inference","domain":"string","description":"The inference if all the Conditions are met."}]}],"fixed":true,"domain":"[valueless]","description":"Contains 1+ Rule items (rule record or rule sub-doc)"},{"name":"MetaRules","items":[{"name":"MetaRule","domain":"enum(All Satisfied, None Satisfied, Atleast One Satisfied)","unique":true,"description":"Meta rule to accomodate what to do when no, all or at least one rule(s) ar satisfied.","identifier":true,"properties":[{"name":"KeyWord","domain":"string","description":"What is the keyword to use to highlight such states. e.g. if no rules are satisfied then according to ACMG, the variant is of Unknown Significance"}]}],"fixed":true,"category":true,"domain":"[valueless]"}]}@
    end
  end
end; end; end
