#!/bin/bash
#
# Starts/Stops/Restarts the genboree processes.
#
# chkconfig: 2345 91 11
# description: Genboree script
# processname: 

### BEGIN INIT INFO
# Provides: genboree
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start, stop, and restart genboree
# Description:  Genboree script to allow easy start/stop/restart
### END INIT INFO

RETVAL=0
GENB_INIT_DIR=/usr/local/brl/local/etc/init.d

# $prog must be executable, else error
[ -x $prog ] || exit 1


SCRIPTS_START=`ls ${GENB_INIT_DIR}/ | grep _init_[0-9]$ | sort -t _ -k 3`
SCRIPTS_STOP=`ls ${GENB_INIT_DIR}/ | grep _init_[0-9]$ | sort -t _ -k 3 -r`


start() {
    for script in ${SCRIPTS_START}
    do
        ${GENB_INIT_DIR}/${script}  start
    done
    RETVAL=$?  # TODO 
    return $RETVAL
}

stop() {
    for script in ${SCRIPTS_STOP}
    do
        ${GENB_INIT_DIR}/${script}  stop
    done
    RETVAL=$?
    return $RETVAL
}

restart() {
   stop
   start
   RETVAL=$?
   return $RETVAL
}

echo ""
case "$1" in
  start)
   start
   RETVAL=$?
   ;;
  stop)
   stop
   RETVAL=$?
   ;;
  restart)
   restart
   RETVAL=$?
   ;;
  *)
   echo $"Usage: $0 {start|stop|restart}"
   RETVAL=1
esac

# TODO
if [ $RETVAL = 0 ] ; then
  echo $'\nSUCCESS\n'
else
  echo $'\nFAILURE:' $progName '"'$1'" command failed, check logs ( exit code' $RETVAL $')\n'
fi

exit $RETVAL 

