#!/bin/bash

# ##########################
# ENVIRONMENT
# ##########################
DIR_SCRIPTS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR_SCRIPTS}/conf_runtime.sh

PID_FILE=${DIR_TARGET}/var/mongodb.pid
LOG_FILE=${DIR_TARGET}/var/mongodb.log
PORT=16001
CMD_START="mongod --fork --dbpath ${DIR_DATA}/mongodb/data --logpath ${LOG_FILE} --logappend --bind_ip localhost --port ${PORT} --pidfilepath ${PID_FILE} --unixSocketPrefix ${DIR_TARGET}/tmp"
CMD_STOP="mongod --shutdown --dbpath ${DIR_DATA}/mongodb/data"

# #########################
# CONFIG PROG
# #########################

start() {
    ${CMD_START}
}

stop() {
    ${CMD_STOP}
}

echo ""
case "$1" in
  start)
   start
   ;;
  stop)
   stop
   ;;
  restart)
   stop
   start
   ;;
  *)
   echo $"Usage: $0 {start|stop|restart}"
   exit 3
esac

exit 0
