#!/bin/bash

# #########################
# ENVIRONMENT
# #########################
DIR_SCRIPTS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR_SCRIPTS}/conf_runtime.sh

export TMPDIR=${DIR_TARGET}/rails/$redmineId/tmp
export TMP_DIR=$TMPDIR
export TEMPDIR=$TMPDIR

umask 002

# #########################
# MAIN
# #########################

RETVAL=0

start() {
    echo -n $"Starting THIN_REDMINE:" $'\n'
    thin -C ${DIR_TARGET}/etc/thin_redmine.conf start
    RETVAL=$?
}

stop() {
    echo -n $"Shutting down THIN_REDMINE:" $'\n'
    thin -C ${DIR_TARGET}/etc/thin_redmine.conf stop
    RETVAL=$?
}

restart() {
    echo -n $"Restarting THIN_REDMINE:" $'\n'
    thin -C ${DIR_TARGET}/etc/thin_redmine.conf restart
    RETVAL=$?
}

echo ""
case "$1" in
  start)
   start
   ;;
  stop)
   stop
   ;;
  restart)
   restart
   ;;
  *)
   echo $"Usage: $0 {start|stop|restart}"
   RETVAL=1
esac


if [ $RETVAL = 0 ] ; then
    echo "**SUCCESS**"
else
    echo "FAILURE: '$0 $1' command failed, check logs ( exit code $RETVAL )"
fi

exit $RETVAL 

