#!/bin/bash

# Tomcat control script designed to allow an easy command line interface to controlling Tomcat
# chkconfig: 345 85 15
# description: Tomcat 5.5 start script

### BEGIN INIT INFO
# Provides: tomcat
# Required-Start: $local_fs $network $remote_fs
# Should-Start: ypbind nscd ldap ntpd xntpd
# Required-Stop: $local_fs $network $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop Tomcat
# Description:  Tomcat control script designed to allow an easy command line interface
### END INIT INFO

##############################################################################
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################


############################################################################
# Adapt the following lines to your configuration
############################################################################
DIR_SCRIPTS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR_SCRIPTS}/conf_runtime.sh
# Set the umask if the system default (usually 022) is not what you want
umask 002
# Where is jsvc, the tomcat service script
DAEMON_HOME=$CATALINA_HOME/bin
DAEMON_EXE=$DAEMON_HOME/jsvc
# What user to run tomcat as?
TOMCAT_USER=genboree
# Where to put the .pid file?
PID_FILE=${DIR_TARGET}/var/tomcat.pid
CATALINA_BASE=$CATALINA_HOME
# file with configuration
source ${DIR_TARGET}/etc/tomcat.conf
CLASSPATH=${JAVA_HOME}/lib/tools.jar:${CATALINA_HOME}/bin/commons-daemon.jar:${CATALINA_HOME}/bin/bootstrap.jar:${CLASSPATH}
############################################################################
# Exports
# - environment variables you want accessible from Tomcat
############################################################################
# CHECK THAT YOUR .libs path is correct here! =>
#export LD_LIBRARY_PATH=${DIR_TARGET}/lib:${DIR_TARGET}/lib64:${DIR_TARGET}/lib64/R:${DIR_TARGET}/mysql/lib:${DIR_TARGET}/mysql/lib/mysql:$CATALINA_HOME/bin/tomcat-native-1.1.24-src/jni/native/.libs
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${CATALINA_HOME}/bin/tomcat-native-1.1.24-src/jni/native/.libs
export LD_PATH=$LD_LIBRARY_PATH
export DISPLAY=:0.0
export TMPDIR=${DIR_TARGET}/tmp
export TMP_DIR=$TMPDIR

############################################################################

ERROR=0


case "$1" in
  start)
    #
    # Start Tomcat
    #
    $DAEMON_EXE $JSVC_OPTS \
    -user $TOMCAT_USER \
    -home $JAVA_HOME \
    -Dcatalina.home=$CATALINA_HOME \
    -Dcatalina.base=$CATALINA_BASE \
    -Djava.io.tmpdir=$TMP_DIR \
    -wait 10 \
    -pidfile $PID_FILE \
    -outfile $CATALINA_HOME/logs/catalina.out \
    -errfile '&1' \
    $CATALINA_OPTS \
    -Djava.awt.headless=true -Djava.library.path=$CATALINA_HOME/bin/tomcat-native-1.1.24-src/jni/native/.libs \
    -cp $CLASSPATH \
    org.apache.catalina.startup.Bootstrap
    #
    # To get a verbose JVM
    #-verbose \
    # To get a debug of jsvc.
    #-debug \
    ERROR=$?
    ;;

  stop)
    #
    # Stop Tomcat
    #
    $DAEMON_EXE $JSVC_OPTS \
    -stop \
    -pidfile $PID_FILE \
    org.apache.catalina.startup.Bootstrap
    ERROR=$?
    ;;

  *)
    echo "Usage tomcat.sh start/stop"
    ERROR=1
    ;;
esac


# ARJ: Print something based on ERROR and what was asked
if [ $ERROR = 0 ] ; then
  echo $'\nSUCCESS: Tomcat "'$1'" command successful ( exit code' $ERROR $')\n'
else
  echo $'\nFAILURE: Tomcat "'$1'" command failed, check logs ( exit code' $ERROR $')\n'
fi
exit $ERROR

