#!/bin/bash


BASEDIR="/usr/local/brl/local/apache/htdocs/webapps/java-bin/TCGA-Reporting"
#PHASE="phaseI-0808"
DATADIR="data"
AMPLICONCOMPLETION_DIR="ampliconCompletion"
GENECOMPLETION_DIR="geneCompletion"
GENECOVERAGE_DIR="geneCoverage"
SAMPLECOMPLETION_DIR="sampleCompletion"
INSTITUTION=""
TYPEOFFILE=""


####### Summary Files
AMPLICONCOMPLETION_FILE="ampliconCompletion.summary"
SAMPLECOMPLETION_FILE="sampleCompletion.summary_new"
SAMPLECOMPLETION_FILEDEST="sampleCompletion.summary"
GENECOVERAGE_FILE="geneCoverage.summary"
GENECOMPLETION_FILE="geneCompletion.summary"

 
if [ $# -lt 2 ]
then
  echo "usage: $0 INSTITUTION PHASEDIR [TYPEOFFILE]"
  exit
fi


############### Variables
INSTITUTION=$1
PHASE=$2

if [ $# -gt 2 ] && [ -n $3 ]
then
  TYPEOFFILE=$3"_"
fi

DESTINATIONDIR=$BASEDIR"/"$PHASE"/"$DATADIR

AMPLICONCOMPLETION_DESTINATION=$DESTINATIONDIR"/"$AMPLICONCOMPLETION_DIR"/"$TYPEOFFILE""$INSTITUTION"_"$AMPLICONCOMPLETION_FILE
SAMPLECOMPLETION_DESTINATION=$DESTINATIONDIR"/"$SAMPLECOMPLETION_DIR"/"$TYPEOFFILE""$INSTITUTION"_"$SAMPLECOMPLETION_FILEDEST
GENECOVERAGE_DESTINATION=$DESTINATIONDIR"/"$GENECOVERAGE_DIR"/"$TYPEOFFILE""$INSTITUTION"_"$GENECOVERAGE_FILE
GENECOMPLETION_DESTINATION=$DESTINATIONDIR"/"$GENECOMPLETION_DIR"/"$TYPEOFFILE""$INSTITUTION"_"$GENECOMPLETION_FILE

localDate=`date +'%Y-%m-%d @ %H:%M:%S (%s)'`
echo "COPYING FILES TO  "$DESTINATIONDIR" -- "$localDate
cp $AMPLICONCOMPLETION_FILE  $AMPLICONCOMPLETION_DESTINATION
cp $SAMPLECOMPLETION_FILE  $SAMPLECOMPLETION_DESTINATION
cp $GENECOVERAGE_FILE  $GENECOVERAGE_DESTINATION
cp $GENECOMPLETION_FILE  $GENECOMPLETION_DESTINATION


localDate=`date +'%Y-%m-%d @ %H:%M:%S (%s)'`
echo "The End  --"$localDate

