#!/bin/bash

####### Programs


FILEFILTER="/usr/local/brl/local/apache/ruby/brl/fileFormats/tcgaParsers/fileFilter.rb"

 
if [ $# -lt 8 ]
then
  echo "usage: $0 AMPLICONFILENAME AMPLICONTOLOCIFILENAME LOCIFILENAME ROIFILENAME ROISEQUENCINGFILENAME ROITOLOCIFILENAME SAMPLESEQUENCINGFILENAME phase"
  exit
fi


################ INPUT Files from Centers

AMPLICONFILENAME=$1
AMPLICONTOLOCIFILENAME=$2
LOCIFILENAME=$3
ROIFILENAME=$4
ROISEQUENCINGFILENAME=$5
ROITOLOCIFILENAME=$6
SAMPLESEQUENCINGFILENAME=$7
phase=$8
termination=".txt"

AMPLICONFOUNDFILENAME=$AMPLICONFILENAME"_"$phase""$termination
AMPLICONMISSINGFILENAME=$AMPLICONFILENAME"_"$phase"_missing"$termination
ROIFOUNDFILENAME=$ROIFILENAME"_"$phase""$termination
ROIMISSINGFILENAME=$ROIFILENAME"_"$phase"_missing"$termination
ROISEQUENCINGFOUNDFILENAME=$ROISEQUENCINGFILENAME"_"$phase""$termination
ROISEQUENCINGMISSINGFILENAME=$ROISEQUENCINGFILENAME"_"$phase"_missing"$termination
SAMPLESEQUENCINGFOUNDFILENAME=$SAMPLESEQUENCINGFILENAME"_"$phase""$termination
SAMPLESEQUENCINGMISSINGFILENAME=$SAMPLESEQUENCINGFILENAME"_"$phase"_missing"$termination


localDate=`date +'%Y-%m-%d @ %H:%M:%S (%s)'`
echo "RUNNING FILE FILTER  ---- "$localDate

$FILEFILTER --ampliconFileName $AMPLICONFILENAME --ampliconFoundFileName $AMPLICONFOUNDFILENAME \
--ampliconMissingFileName $AMPLICONMISSINGFILENAME --ampliconToLociFileName $AMPLICONTOLOCIFILENAME \
--lociFileName $LOCIFILENAME --roiFileName $ROIFILENAME --roiFoundFileName $ROIFOUNDFILENAME \
--roiMissingFileName $ROIMISSINGFILENAME --roiSequencingFileName $ROISEQUENCINGFILENAME \
--roiSequencingFoundFileName $ROISEQUENCINGFOUNDFILENAME --roiSequencingMissingFileName $ROISEQUENCINGMISSINGFILENAME \
--roiToLociFileName $ROITOLOCIFILENAME --sampleSequencingFileName $SAMPLESEQUENCINGFILENAME \
--sampleSequencingFoundFileName $SAMPLESEQUENCINGFOUNDFILENAME \
--sampleSequencingMissingFileName $SAMPLESEQUENCINGMISSINGFILENAME

mkdir $phase
mv $AMPLICONFOUNDFILENAME $ROIFOUNDFILENAME $ROISEQUENCINGFOUNDFILENAME $SAMPLESEQUENCINGFOUNDFILENAME $phase"/"
mkdir $phase"_missing"
mv $AMPLICONMISSINGFILENAME $ROIMISSINGFILENAME $ROISEQUENCINGMISSINGFILENAME $SAMPLESEQUENCINGMISSINGFILENAME $phase"_missing/"
localDate=`date +'%Y-%m-%d @ %H:%M:%S (%s)'`
echo "The End  --"$localDate

