<%@ page import="javax.servlet.http.*, java.util.*,
 org.genboree.dbaccess.*, org.genboree.util.*, org.genboree.upload.*" %>

<HTML>
<head>
<title>Creating a Custom Link</title>
<link rel="stylesheet" href="/styles/jsp.css<%=jsVersion%>" type="text/css">
<meta HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=iso-8859-1'>
</head>
<BODY>

<%@ include file="include/header.incl" %>

  	
      	<br><H3 align="center">Creating a Custom Link</H3>
        <P>Custom Links are HTTP &quot;GET&quot; style URLs. Annotation fields
        are passed in the name value pairs. Using specific tags in your Custom
        Link, you specify where the annotation field(s) should be placed in
        your URL.</P>
        
        <TABLE BORDER="1" CELLSPACING="0" CELLPADDING="3">
        <TBODY>
        <TR>
        <TD>
	<H5>For example:</H5>
	http://genome.ucsc.edu/cgi-bin/hgTracks?position=<B>$entryPoint</B>:<B>$from</B>-<B>$to</B>&amp;hgsid=34721529
	</TD>
	</TR>
	</TBODY>
	</TABLE>
	<P>
	In this example, the Annotation's <B>entrypoint</B> (chromosome name), 
	<B>start</B>, and <B>end</B> fields are set as the value for the position argument to provide a
	link to the equivalent region in the UCSC browser.
	</P>
	
	<H5>Making Custom Links</H5>
        To generate a custom link you need to identify the base url and the 
        necessary parameters. For example:</P>
        <P>&nbsp;&nbsp;&nbsp;&nbsp;Base URL: <FONT COLOR="blue">http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?</FONT></P>
        <P>&nbsp;&nbsp;&nbsp;&nbsp;Parameters: <FONT COLOR="blue">position={your variable}:{your variable}-{your variable}</FONT> and <FONT COLOR="blue">hgsid=34721529</FONT></P>
        <UL>
        	<LI>Spaces should be replaced with plus (+) signs.</LI>
        	<LI>Name-Value parameters should be concatenated using the ampersand symbol (&amp;).</LI>
        </UL>
        </P>
        <H5>Recognized Tags</H5>
        <P>
        Genboree provide a link-editig module to help you generate custom
        links for you annotations and to associate them with the proper track(s).
        Any field of an annotation can be used in a custom link by using the
        appropriate tags.
        </P>
        The tags correspond closely to the LFF columns used
        to upload the annotations. In fact, in general the tag name is the same
        as the corresponding LFF column name, but prefixed with a &quot;<B>$</B>&quot; :
        
 	<UL>
 		<LI><B>$class</B></LI>
		<LI><B>$name</B></LI>
		<LI><B>$type</B></LI>
		<LI><B>$subtype</B></LI>
		<LI><B>$reference</B></LI>
		<LI><B>$start</B></LI>
		<LI><B>$stop</B></LI>
		<LI><B>$strand</B></LI>
		<LI><B>$phase</B></LI>
		<LI><B>$score</B></LI>
		<LI><B>$tstart</B></LI>
		<LI><B>$tend</B></LI>
	</UL>
        <P>Which correspond to the column names of the lff annotation section:</P>
        <P>
        &nbsp;&nbsp;&nbsp;&nbsp;[annotations]<br>
        &nbsp;&nbsp;&nbsp;&nbsp;class&nbsp;&nbsp;name&nbsp;&nbsp;type&nbsp;&nbsp;subtype&nbsp;&nbsp;ref&nbsp;&nbsp;start&nbsp;&nbsp;stop&nbsp;&nbsp;strand&nbsp;&nbsp;phase&nbsp;&nbsp;score&nbsp;&nbsp;tstart&nbsp;&nbsp;tend
        </P>
        <P>In addition, we support several synonyms: </P>
        <UL>
        	<LI><B>$targetstart</B> = <B>$tstart</B></LI>
        	<LI><B>$targetstop</B> = <B>$tend</B></LI>
        	<LI><B>$end</B> = <B>$stop</B></LI>
        </UL>
        <P>
        And a special tag <B>$stripName</B> whose value is generated by removing any information 
        after the last period (&quot;.&quot;) from the value of the <B>$name</B> tag, which is useful
        for removing version numbers or unique suffices.
        </P>
        <TABLE BORDER="1" CELLSPACING="0" CELLPADDING="3">
        <TBODY>
        <TR>
        <TD>
	<H5>Example:</H5>
	http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Search&amp;db=PubMed&amp;term=<B>$stripName</B>&amp;doptcmdl=DocSum
	</TD>
	</TR>
	</TBODY>
	</TABLE>

	<p><input type="button" value="Close" onclick="window.close();" class="btn" ></p>

<%@ include file="include/footer.incl" %>
</BODY>
</HTML>
