<%@ page import="javax.servlet.http.*,
  java.io.*, java.util.*,
  org.genboree.dbaccess.*, org.genboree.util.*, org.genboree.upload.*" %>
<%@ include file="include/fwdurl.incl" %>
<%@ include file="include/userinfo.incl" %>
<%!
	static final File galleryDir =
		new File( System.getProperty("catalina.home",org.genboree.util.Constants.GENBOREE_HTDOCS), "gallery" );
%>
<%
    response.addDateHeader( "Expires", 0L );
    response.addHeader( "Cache-Control", "no-cache, no-store" );
	

	String delId = request.getParameter("delId");
	String editId = request.getParameter("editId");
	File dirFile = null;
	String fid = delId;
	if( fid == null ) fid = editId;
	if( fid != null ) try
	{
		dirFile = new File( galleryDir, fid );
		if( !dirFile.exists() || !dirFile.isDirectory() ) dirFile = null;
		File infoFile = new File( dirFile, "dirinfo" );
		Properties props = new Properties();
		FileInputStream fin = new FileInputStream( infoFile );
		props.load( fin );
		fin.close();
		String dbName = props.getProperty( "databaseName" );
		String acsCode = Refseq.fetchUserAccess( db, dbName, userInfo[2] );
		if( acsCode == null ) dirFile = null;
		else if( acsCode.equals("r") && delId != null ) dirFile = null;
	} catch( Exception ex00 ) { dirFile = null; }
	
	if( dirFile != null && delId != null ) try
	{
		FileKiller.clearDirectory( dirFile );
		dirFile.delete();
	} catch( Exception ex01 ) {}
	
	if( dirFile != null && editId != null ) try
	{
		File f = new File( dirFile, "vgpdesign.xml" );
    int userId = Util.parseInt(myself.getUserId(), -1);
    if( f.exists() )
		{
			FileInputStream fin = new FileInputStream( f );
			VGPaint vgp = new VGPaint();
			vgp.deserialize( fin );
			fin.close();
			mys.setAttribute( "vgp_file_uploaded", "1" );
			mys.setAttribute( "VGPaint", vgp );
			String refSeqId = vgp.fetchRefSeqId( db );
			if( !refSeqId.equals("#") )
			{
				String descr = vgp.getDescription();
				String dsn = vgp.getDsnSource();
				vgp.initDBaccess( db, refSeqId, userId );
				vgp.setDsnSource( dsn );
				vgp.setDescription( descr );
				mys.setAttribute( "refSeqId", refSeqId );
			}
			mys.setAttribute( "vgp_reset", "yes" );
			GenboreeUtils.sendRedirect(request,response,  "/java-bin/vgp_step1.jsp" );
			return;
		}
	} catch( Exception ex02 ) {}
	
	
	File[] galleryList = galleryDir.listFiles();
%>

<HTML>
<head>
<title>Bioinformatics Research Laboratory - VGPaint</title>
<link rel="stylesheet" href="/styles/jsp.css<%=jsVersion%>" type="text/css">
<meta HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=iso-8859-1'>
</head>
<BODY>

<%@ include file="include/header.incl" %>
<%@ include file="include/navbar.incl" %>
<br>

<table border="0" cellspacing="0" cellpadding="2">
<tbody>

<% if( !is_public ) { %>
<form name="vgp" action="vgp.jsp" method="post"
  ENCTYPE="multipart/form-data">
  <input id="cmdNext" name="cmdNext" type="hidden" value='Next'>
  <tr>
  	<td rowspan="2" class="form_body" valign="top">
	  <strong>Use&nbsp;Existing<br> Visualization&nbsp;Design</strong>
	</td>
  	<td colspan="2" class="form_body">
	  <input type="file" id="upload_vgp" name="upload_vgp"
		class="txt" style="width:440">
	</tr>
  <tr>
	<td colspan="2" class="form_body">
	  <input type="submit" name="need_edit" id="need_edit"
	   class="btn" style="width:90"
	   value="Edit">&nbsp;
	  <input type="submit" name="view_only" id="view_only"
	   class="btn" style="width:90"
	   value="View">
	</td>
  </tr>
  <tr>
	<td colspan="3">
	  <input type="button" value="Make A New Design" class="btn"
	  onclick="document.vgpnew.submit()">
	</td>
  </tr>
</form>

  <tr>
	<td colspan="3" align="center" valign="middle" height="24"></td>
  </tr>

<form name="vgpnew" action="vgp.jsp" method="post"
  ENCTYPE="multipart/form-data">
  <input id="cmdNext" name="cmdNext" type="hidden" value='Next'>
</form>
<% } %>

  <tr>
	<td valign="top">
	<font color="#5947B3" size="-1"><strong>
	&nbsp;&nbsp;VGP Gallery
	</strong></font>
	</td>
	<td colspan="2">
	<font size="-2"><strong>
	A repository of images generated by
	<a href="#about">Virtual Genome Painting</a>.
	</strong></font>
	</td>
  </tr>

  <tr>
	<td colspan="3" align="center" valign="middle" height="12"></td>
  </tr>
  
  <tr>
	<td colspan="3">
	VGP Paint Visualization of
	<a href="http://brl.bcm.tmc.edu/pash/index.html">Pash</a>
	comparisons between three (3) genomes:<br>
	  <table width="100%" border="0" cellspacing="2" cellpadding="4">
	  <tbody>
	  
	  <tr>
		<td class="form_body"><strong>Name</strong></td>
		<td class="form_body"><strong>Description</strong></td>
		<td class="form_body"><strong>Version</strong></td>
		<td class="form_body">&nbsp;</td>
		<td class="form_body">&nbsp;</td>
		<td class="form_body">&nbsp;</td>
	  </tr>
	  
	  <tr>
		<td>
		<a href="syntenyCompact.jsp?specieId=8">
		<img height=62 alt="Rat" src="/images/rat_thumb.gif" width=100 border=0></a><br>
		Rat Synteny
		</td>
		<td><a href="syntenyCompact.jsp?specieId=8">Rat-Centric:</a>
			Human and Mouse similarites on the Rat genome
		</td>
		<td>1.0</td>
		<td><a href="syntenyCompact.jsp?specieId=8">View</a></td>

<% if( !is_public ) { %>
		<td><a href="vgp_step1.jsp?db=ratSynteny">Edit</a></td>
<% } else {%>
		<td>&nbsp;</td>
<% } %>

		<td>&nbsp;</td>
	  </tr>

	  <tr>
		<td class="form_body" height="2"></td>
		<td class="form_body" height="2"></td>
		<td class="form_body" height="2" colspan="4"></td>
	  </tr>
	  
	  <tr>
		<td>
		<a href="syntenyCompact.jsp?specieId=9">
		<img height=62 alt="Mouse" src="/images/mouse_thumb.gif" width=100 border=0></a><br>
		Mouse Synteny
		</td>
		<td><a
			href="syntenyCompact.jsp?specieId=9">Mouse-Centric:</a>
			Human and Rat similarites on the Mouse genome
		</td>
		<td>1.0</td>
		<td><a href="syntenyCompact.jsp?specieId=9">View</a></td>
<% if( !is_public ) { %>
		<td><a href="vgp_step1.jsp?db=mouseSynteny">Edit</a></td>
<% } else {%>
		<td>&nbsp;</td>
<% } %>
		<td>&nbsp;</td>
	  </tr>
	  
	  <tr>
		<td class="form_body" height="2"></td>
		<td class="form_body" height="2"></td>
		<td class="form_body" height="2" colspan="4"></td>
	  </tr>
	  
	  <tr>
		<td>
		<a href="syntenyCompact.jsp?specieId=7">
		<img height=62 alt="HUman" src="/images/human_thumb.gif" width=100 border=0></a><br>
		Human Synteny
		</td>
		<td><a
			href="syntenyCompact.jsp?specieId=7">Human-Centric:</a>
			Rat and Mouse similarites on the Human genome
		</td>
		<td>1.0</td>
		<td><a href="syntenyCompact.jsp?specieId=7">View</a></td>
<% if( !is_public ) { %>
		<td><a href="vgp_step1.jsp?db=humanSynteny">Edit</a></td>
<% } else {%>
		<td>&nbsp;</td>
<% } %>
		<td>&nbsp;</td>
	  </tr>
	  
<%
	int i;
	boolean first_line = true;
	for( i=0; i<galleryList.length; i++ )
	{
		File dir = galleryList[i];
		if( !dir.isDirectory() ) continue;
		File dirInfo = new File( dir, "dirinfo" );
		if( !dirInfo.exists() ) continue;
		Properties props = new Properties();
		FileInputStream fin = new FileInputStream( dirInfo );
		props.load( fin );
		fin.close();
		String dbName = props.getProperty( "databaseName" );
		String descr = props.getProperty( "description" );
		if( dbName == null || descr == null ) continue;
		String acsCode = Refseq.fetchUserAccess( db, dbName, userInfo[2] );
		if( acsCode == null ) continue;
		String tgtUrl = "/java-bin/vgp_view.jsp?id="+dir.getName();
		
		String delUrl = acsCode.equals("r") ? "&nbsp;" :
			"<a href=\"/java-bin/VGPaint.jsp?delId="+dir.getName()+"\">Delete</a>";
		String editUrl = is_public ? "&nbsp;" :
			"<a href=\"/java-bin/VGPaint.jsp?editId="+dir.getName()+"\">Edit</a>";
		
		String sepH = "2";
		if( first_line )
		{
			first_line = false;
			sepH = "6";
		}
%>
	  <tr>
		<td class="form_body" height="<%=sepH%>"></td>
		<td class="form_body" height="<%=sepH%>"></td>
		<td class="form_body" height="<%=sepH%>" colspan="4"></td>
	  </tr>

	  <tr>
		<td>&nbsp;</td>
		<td>
		<a href="<%=tgtUrl%>"><%=Util.htmlQuote(descr)%></a>
		</td>
		<td>&nbsp;</td>
		<td><a href="<%=tgtUrl%>">View</a></td>
		<td><%=editUrl%></td>
		<td><%=delUrl%></td>
	  </tr>
<%
	}	
%>
	  
	  </tbody>
	  </table>
	</td>
  </tr>	
  
  <tr>
	<td colspan="3" align="center" valign="middle" height="24"><IMG height=1 alt=""
	 src="/images/bluemed1px.gif" width=480 
     border=0></td>
  </tr>

  <tr>
	<td colspan="3">
	<font color="#5947B3" size="-1"><strong>
	&nbsp;&nbsp;About VGP Paint
	</strong></font>
	</td>
  </tr>
  <tr>
	<td colspan="3">
<a name="about"></a>
<UL>
<LI>The VGP Merge program merges computationally-derived 
annotations, such as orthologous anchors. 
<LI> VGP Paint generates genome-scale visualizations 
using VGP Merged annotations �outlines� stored at 
the <a href="http://www.genboree.org/">Genboree server</a>. 
<LI>VGP Paint program retrieves selected outlines, fills 
the outlines and their logical combinations with user-defined 
colors, and creates visualizations in various formats 
suitable for data-driven discovery or publication. 
<LI>The<a href="http://www.genboree.org/"> Genboree server</a> provides a public repository 
of outlines such as those produced by VGP Merge and 
supports password-protected pre-publication access 
by geographically distributed collaborators.
</UL>
	</td>
  </tr>
  
  <tr>
	<td colspan="3" align="center" valign="middle" height="12"><IMG height=1 alt=""
	 src="/images/bluemed1px.gif" width=480 
     border=0></td>
  </tr>

</tbody>
</table>

<%@ include file="include/footer.incl" %>

</BODY>
</HTML>
