USE redmine;

-- ==================== wiki_pages
INSERT INTO wiki_pages(id,wiki_id,title,created_on,protected,parent_id) VALUES(107,1,'Menu','2015-03-31 10:08:28 -0500',0,NULL);
INSERT INTO wiki_pages(id,wiki_id,title,created_on,protected,parent_id) VALUES(108,1,'SPLASH_CONTENT','2015-03-31 10:09:40 -0500',0,107);
INSERT INTO wiki_pages(id,wiki_id,title,created_on,protected,parent_id) VALUES(109,1,'DEFAULT_CONFIG','2015-03-31 10:10:14 -0500',0,107);
INSERT INTO wiki_pages(id,wiki_id,title,created_on,protected,parent_id) VALUES(112,1,'FOUR_ZERO_FOUR','2015-04-07 12:24:12 -0500',0,107);

-- ==================== wiki_contents
INSERT INTO wiki_contents(id,page_id,author_id,text,comments,updated_on,version) VALUES(107,107,1,'------------------------------------\r\n\r\nCURRENT Web Site Content\r\n\r\n------------------------------------\r\n* Page Content\r\n** [[SPLASH_CONTENT]]\r\n* Page Config\r\n** [[DEFAULT_CONFIG]]\r\n* Page with 404 error\r\n** [[FOUR_ZERO_FOUR]]','','2015-04-07 12:23:15 -0500',2);
INSERT INTO wiki_contents(id,page_id,author_id,text,comments,updated_on,version) VALUES(108,108,1,'\r\nID: CTA\r\ntype: call_to_action\r\nsection_id: cta\r\nsection_class: white-bg\r\norientation: text_left\r\nh1: bringing data and <br class=\"hidden-sm hidden-md\">tools together\r\nh2: Genboree is a web-based platform for multi-omic research and data analysis using the latest bioinformatics tools.\r\np: You can upload your data and perform various analyses using a “drag and drop” user interface.  Keep it private or share with collaborators.  Bioinformatics tools and computational infrastructure are available for researchers who may not have programming expertise, or the time to pursue technical programming and/or scripting.\r\nlink_text: Visit genboree.org to learn more ...\r\nlink: http://genboree.org\r\nimage_path:  /attachments/download/158/genboree-blue-dna-strand-fit.jpg\r\nhtml_entity: <i class=\"icon-network\"></i>\r\nalt_image_text: web-based platform for multi-omic research and data analysis\r\n\r\n\r\nID: style_1\r\ntype: style\r\n<style>\r\n#custom_html_entity_class {\r\ncolor: #f89829;\r\nfloat: right;\r\nfont-size: 250px;\r\nmargin-top: 0px;\r\n}\r\n.black-bg, .blue-bg, .white-bg {\r\npadding-bottom: 0px;\r\n}\r\n.black-bg {\r\npadding-top: 0px;\r\n}\r\n#cta h1 {\r\nmargin-bottom: 0px;\r\n}\r\n</style>','','2015-03-31 10:09:40 -0500',1);
INSERT INTO wiki_contents(id,page_id,author_id,text,comments,updated_on,version) VALUES(109,109,1,'ID: CONFIG\r\npage_title: Genboree Bioinformatics\r\nmeta_tags: genboree, bioinformatics, research, tools\r\n\r\nID: HEADER_MAIN\r\nleft_navbar_brand: Genboree\r\nleft_navbar_brand_link: /\r\nlink_1: /java-bin/workbench.jsp\r\nlink_text_1: Workbench\r\nlink_2: /redmine\r\nlink_text_2: Redmine\r\n\r\nID: FOOTER_MAIN\r\nname: Genboree\r\nnavbar_brand: Genboree\r\nh4: BIOINFORMATICS RESEARCH LABORATORY\r\np: Baylor College of Medicine\r\nstreetAddress: One Baylor Plaza,\r\nroomLocation:  MS:BCM225 Suite 400D\r\naddressLocality: Houston\r\naddressRegion: TX\r\npostalCode: 77030\r\ninstitution_logo_path: /attachments/download/14/genboree-baylor.png\r\ninstitution_logo_alt_text: Baylor College of Medicine\r\ninstitution_logo_link: http://www.bcm.edu\r\nlab_logo_path: /attachments/download/15/genboree-bioinformatics-research-laboratory.png\r\nlab_logo_alt_text: Bioinformatics Research Laboratory\r\nlab_logo_link: bioinformatics_research_laboratory\r\ncopyright: 2001 - 2016 Baylor College of Medicine\r\n\r\nID: FOOTER_SUBGROUP_1\r\nh4: GENBOREE\r\nlink_text_1: genboree.org\r\nlink_1: http://genboree.org\r\n\r\nID: GOOGLE_ANALYTICS\r\ntracking_code: none\r\n\r\nID: GENBOREE_ACCOUNT\r\nlink_text_1: New Account\r\nlink_1: /java-bin/regform.jsp\r\nlink_text_2: Recover Password\r\nlink_2: /java-bin/forgotten.jsp','','2015-03-31 15:17:41 -0500',2);
INSERT INTO wiki_contents(id,page_id,author_id,text,comments,updated_on,version) VALUES(112,112,1,'image_path: /attachments/download/37/dna-163710_1280.jpg\r\nalt_image_text: double stranded DNA\r\nh1: Stranded?\r\nh2: Broken link or misbehaving keyboard?\r\np_info: If you\'re looking to get some basic information about Genboree, please check the links in the header / footer or visit our getting started page:\r\nlink: /site\r\nlink_text: Main page\r\n','','2015-04-07 12:38:15 -0500',2);

-- ==================== attachments
INSERT INTO attachments(id,container_id,container_type,filename,disk_filename,filesize,content_type,digest,downloads,author_id,created_on,description,disk_directory) VALUES(158,1,'Project','genboree-blue-dna-strand-fit.jpg','150304141358_genboree-blue-dna-strand-fit.jpg',70248,'','538f3fd6a5b0b49d9bd8b24ccfad2b78',0,1,'2015-03-04 14:13:58 -0600','','2015/03');
INSERT INTO attachments(id,container_id,container_type,filename,disk_filename,filesize,content_type,digest,downloads,author_id,created_on,description,disk_directory) VALUES(14,1,'Project','genboree-baylor.png','141017091057_genboree-baylor.png',7505,'','380fea48f251a0e9066a44638d9cb067',0,1,'2014-10-17 09:10:57 -0500','','2014/10');
INSERT INTO attachments(id,container_id,container_type,filename,disk_filename,filesize,content_type,digest,downloads,author_id,created_on,description,disk_directory) VALUES(15,1,'Project','genboree-bioinformatics-research-laboratory.png','141017091106_genboree-bioinformatics-research-laboratory.png',10528,'','a04e5c6260925b0339ba52d288db8fb3',0,1,'2014-10-17 09:11:06 -0500','','2014/10');
INSERT INTO attachments(id,container_id,container_type,filename,disk_filename,filesize,content_type,digest,downloads,author_id,created_on,description,disk_directory) VALUES(37,1,'Project','dna-163710_1280.jpg','141024092230_dna-163710_1280.jpg',132486,'','9d2621acaee6959122f4418ac98ca0f0',0,1,'2014-10-24 09:22:30 -0500','','2014/10');
